export const UPDATE_COINS_DATA = 'UPDATE_COINS_DATA';
export const UPDATE_COINS_DATA_SUCCESS = 'UPDATE_COINS_DATA_SUCCESS';
export const UPDATE_COINS_DATA_ERROR = 'UPDATE_COINS_DATA_ERROR';

export const LOAD_SEARCH_VALUES = 'LOAD_SEARCH_VALUES';
export const LOAD_CHART_DATA = 'LOAD_CHART_DATA';